---
title: "TakeUp Statistical Model"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Static Take-up Model

## Model subscripts 

* $i$: individuals
* $j$: clusters (villages)
* $k$: strata (counties)

## Variables

* $Y_i \in \{0, 1\}$, observed take-up.
* $\mathbf{Z}_i$, assigned treatment: incentive treatments, SMS treatment, distance treatment 
* $\mathbf{X}_i$, covariates: phone-ownership, and name-matching indicators. 

## Likelihood Model

This is the model's likelihood, the data generating process for observed outcomes:

$$
\begin{aligned}
\Pr[Y_i = 1 | \mathbf{Z}_i, \mathbf{X}_i, \theta_{j[i]}] &= g^{-1}(\eta_i | \theta_{j[i]}) \\
\eta_i &=  f(\mathbf{Z}_i, \mathbf{X}_i | \theta_{j[i]})   
\end{aligned}
$$

where 

* $g$ is a binary link function (e.g., logit or probit link functions).
* $f$ is a linear function of $\mathbf{Z}$ and $\mathbf{X}$^[I'm writing it this way so I don't have to write the whole linear model with treatment indicators, covariates and, their interactions. I can specify it separately, it would just distract from the overall model here.]. 
* $\theta_j = (\alpha_j, \beta_j)'$, where $\alpha_j$ and $\beta_j$ are the model parameters for the village-level intercept and the village-level vector of slope coefficients, respectively.

## Parameter Model

This section describe the hierarchical model for parameters. Distribution that have $\mathtt{Multi}$ prefix are multivariate distributions and distributions with $\mathtt{Half}$ prefix are restricted to have non-negative values. 

The vector of village-level parameters has the following multivariate distribution:

$$
\forall j: \theta_j \sim \mathtt{MultiStudentT}(\nu^\text{village}, \theta_{k[j]}, \Sigma_{k[j]}^\text{village})
$$
while the county-level parameters have the following distribution
$$
\forall k: \theta_k \sim \mathtt{MultiStudentT}(\nu^\text{county}, \theta^o, \Sigma^\text{county})
$$
where $\theta^o = (\alpha^o, \beta^o)$ are the hyperparameters of the linear model:
$$
\begin{aligned}
\alpha^o &\sim \mathtt{Normal}(0, 5) \\
\beta^o &\sim \mathtt{MultiNormal}(0, \mathsf{diag}(1))
\end{aligned}
$$
($\mathsf{diag}(x)$ is a matrix with the diagonal vector $x$.)

The covariance matrices for $\theta_j$ and $\theta_k$ are defined as
$$
\begin{aligned}
\forall k: \Sigma_k^\text{village} &= \mathsf{diag}(\sigma^\text{village}) \Omega_k^\text{village} \mathsf{diag}(\sigma^\text{village}) \\
\Sigma^\text{county} &= \mathsf{diag}(\sigma^\text{county}) \Omega^\text{county} \mathsf{diag}(\sigma^\text{county})
\end{aligned}
$$
where $\Omega_k^\text{village}$ and $\Omega^\text{county}$ are correlation matrices with their own prior distributions.

Other hyper parameters have the following prior distributions
$$
\begin{aligned}
\nu^\text{village} &\sim \Gamma(2, 0.1) \\
\nu^\text{county} &\sim \Gamma(2, 0.1) \\
\sigma^\text{village} &\sim \mathtt{HalfMultiNormal}(0, \mathsf{diag}(1)) \\
\sigma^\text{county} &\sim \mathtt{HalfMultiNormal}(0, \mathsf{diag}(1)) \\
\end{aligned}
$$

## Posterior Distribution of Model Parameters

Let $\theta$ be a vector of all linear model parameters at all levels and $\phi$ is a vector of all hyperparameters, and $\mathbf{Y}$ is a matrix of all observed outcomes. To conduct our inference we need to calculate the distribution
$$
p(\theta,\phi|\mathbf{Y}^\text{observed}, \mathbf{Z}^\text{observed}, \mathbf{X}) = p(\mathbf{Y}^\text{observed} | \mathbf{Z}^\text{observed}, \mathbf{X}, \theta, \phi) p(\theta | \phi) p(\phi)
$$

## Inference

After calculating the posterior distribtution of the model's parameters we want to be able to calculate, for any two treatments $z$ and $z'$, the distribution of the average treatment effect
$$
\frac{1}{N} \Sigma_i Y_i(z) - Y_i(z')
$$

Since we only observe at most one outcome of $Y_i(\cdot)$, we need to quantify the distribution of _missing_ counterfactuals:
$$
p(\mathbf{Y}^\text{missing} | \mathbf{Y}^\text{observed}, \mathbf{Z}^\text{observed}, \mathbf{Z}^\text{missing}, \mathbf{X}) = \int p(\mathbf{Y}^\text{missing} | \mathbf{Z}^\text{missing}, \mathbf{X}, \theta, \phi) \cdot p(\theta,\phi|\mathbf{Y}^\text{observed}, \mathbf{Z}^\text{observed}, \mathbf{X})\, d\theta d\phi
$$

# Beliefs and Knowledge Model

## Model subscripts 

* $i$: individuals
* $j$: clusters (villages)

## Variables

* $Y_i^\text{rec} \in \{0, 1, \ldots, 10\}$, the number of of individuals recognized (from a list of 10 randomly selected community members).
* $Y_i^\text{2ord} \in \{0, 1, \ldots, Y_i^\text{rec}\}(z)$, second-order beliefs about the $Y_i^\text{rec}$ recognized community members. $\overline{Y}^\text{ 2ord,fp}(z)$ is the estimated proportion of $X^\text{degree}_i$.
* $Y_i^\text{1ord} \in \{0, 1, \ldots, Y_i^\text{rec}\}$, first-order beliefs about the $Y_i^\text{rec}$ recognized community members. $\overline{Y}^\text{1ord,fp}(z)$ is the estimated proportion of $X^\text{degree}_i$.
* $N_j \in \mathcal{Z}^+$, the population size of village $j$ (observed from the census).
* $X_i^\text{degree} \in \{Y_i^\text{rec}, \ldots, N_{j[i]}\}$, the estimated number of community members $i$ recognizes.
* $\mathbf{Z}_i$, assigned treatment: incentive treatments, SMS treatment, distance treatment 

## Likelihood Model

### Social connectness or recognition

The first stage is to impute each respondents' recognition degree by estimating a parameteric binomial model. $g$ is a link function (e.g. logit). One thing doesn't makes sense here: $\delta^\text{rec}_{j}$ is the coefficient for a village level independent variable, $N_j$. It seems like $\delta^\text{rec}_j$ should just be a village level random effect or make it a county level parameter.

$$
\begin{aligned}
  Y_i^\text{rec} &\sim \mathtt{Binomial}(10, p_i^\text{rec}) \\
  p_i^\text{rec} &= g^{-1}(\alpha_i^\text{rec} + \delta_{j[i]}^\text{rec}\cdot N_{j[i]}) \\
  X_i^\text{degree} &= Y_i^\text{rec} + p^\text{rec}_i \cdot(N_{j[i]} - 10)  
\end{aligned}
$$

$X_i^\text{degree}$ is imputed by adding the known $Y_i^\text{rec}$ with the estimated number of community members (and not asked about in the survey) recognized.

### Second-order beliefs

Same as above but with treatment assignment potentially having a causal effect. Same comment as above about parameter levels.

$$
\begin{aligned}
  Y_i^\text{2ord}(\mathbf{Z}_i) &\sim \mathtt{Binomial}(Y^\text{rec}_i, p_i^\text{2ord}(\mathbf{Z}_i)) \\
  p_i^\text{2ord}(\mathbf{z}) &= g^{-1}(\alpha_i^\text{2ord} + \mathbf{z}\cdot \beta_i^\text{2ord} + \delta_i^\text{2ord}\cdot N_{j[i]}) \\
  \overline{Y}^\text{ 2ord,fp}(\mathbf{Z}_i) &= \frac{Y_i^\text{2ord} + p_i^\text{2ord}(\mathbf{Z}_i)\cdot p_i^\text{rec}\cdot (N_{j[i]} - 10)}{X_i^\text{degree}}
\end{aligned} 
$$
The number of community members $i$ has second-order beliefs^[In the current model $Y_i^\text{2ord} = 1 \iff$ $i$ reports yes/no.] is the sum of the observed sampled $Y_i^\text{2ord}$ and the estimated beliefs about the remaining population not asked about, $p_i^\text{rec}\cdot(N_{j[i]} - 10)$.

For unobserved (missing) treatment $\mathbf{z}^\text{missing}$ we impute $\overline{Y}^\text{ 2ord,fp}(\mathbf{z}^\text{missing})$ as
$$
\overline{Y}^\text{ 2ord,fp}(\mathbf{z}^\text{missing}) = \frac{p_i^\text{2ord}(\mathbf{z}^\text{missing})\cdot p_i^\text{rec}\cdot N_{j[i]}}{X_i^\text{degree}}
$$

### First-order beliefs

The first-order beliefs model is the same as the second-order model.