---
title: "Social Knowledge"
author:
- Anne Karing^[University of California Berkeley]
- Karim Naguib^[Evidence Action]
output:
  html_notebook:
    fig_align: "center"
    fig_caption: yes
    fig_height: 5
    fig_width: 8
    number_sections: yes
    theme: flatly
    toc: yes
    toc_float:
      collapsed: false
      smooth_scroll: false
    toc_depth: 5
header-includes:
   - \usepackage{bbm}
date: "`r format(Sys.time(), '%B %d, %Y')`"
---

```{r, echo=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r setup, include=FALSE}
library(magrittr)
library(plyr)
library(tidyverse)
library(lubridate)
library(forcats)
library(haven)
library(broom)
library(ggrepel)
library(sp)
library(rgeos)
library(ggmap)
library(knitr)

library(rstan)
library(bayesplot)

library(econometr)

source(file.path("rct-design-fieldwork", "takeup_rct_assign_clusters.R"))
source("analysis_util.R")

knitr::read_chunk("analysis_util.R", labels = "analysis-util")

wgs.84 <- "+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"
kenya.proj4 <- "+proj=utm +zone=36 +south +ellps=clrk80 +units=m +no_defs"

options(dplyr.show_progress = FALSE, digits = 4)
```

```{r load-data, include=FALSE}
load(file.path("data", "analysis.RData"))
```

# Qualitative Analysis

```{r}
endline.know.table.data %>% 
  filter(know.table.type == "table.A", !is.na(relationship)) %>% 
  mutate(relationship = fct_infreq(relationship) %>% fct_relabel(str_to_title)) %>% {
    ggplot(.) +
      geom_bar(aes(relationship, y = ..count../sum(..count..)), alpha = 0.5, color = "black") + 
      labs(x = "Relationship", y = "Proportion", 
           title = "Reported Relationships", caption = sprintf("Number of knowledge queries: %d", nrow(.))) +
      scale_y_continuous(breaks = seq(0, 1, 0.1))
  }
```

```{r}
endline.know.table.data %>% 
  filter(know.table.type == "table.A", recognized == "yes") %>% 
  mutate(relationship = fct_infreq(relationship) %>% fct_relabel(str_to_title),
         dewormed = str_to_title(dewormed)) %>% 
  group_by(relationship) %>% 
  mutate(rel.size = n()) %>% 
  group_by(dewormed, add = TRUE) %>% 
  summarize(prop = n()/first(rel.size)) %>% 
  ungroup %>% {
    ggplot(., aes(x = relationship, group = dewormed)) +
      geom_col(aes(y = prop, fill = dewormed), position = "dodge", alpha = 0.5, color = "black") + 
      labs(x = "Relationship", y = "Proportion", title = "Reported Others' Deworming", subtitle = "Table A only",
           caption = "Proportions are relative to relationship group.") +
      scale_y_continuous(breaks = seq(0, 1, 0.1)) +
      scale_fill_discrete("Other Dewormed")
  }
```

```{r, fig.height=6}
# endline.know.table.data %>% 
#   filter(know.table.type == "table.A", recognized == "yes") %>% 
#   # group_by(respondent.dewormed.any, assigned.treatment, actual.other.dewormed.any.either) %>% 
#   group_by(assigned.treatment, actual.other.dewormed.any.either) %>% 
#   mutate(rel.size = n()) %>% 
#   group_by(dewormed, add = TRUE) %>% 
#   summarize(prop = n()/first(rel.size)) %>% 
#   ungroup %>% {
#     ggplot(., aes(x = actual.other.dewormed.any.either, group = dewormed)) +
#       geom_col(aes(y = prop, fill = dewormed), position = "dodge", alpha = 0.5, color = "black") + 
#       labs(x = "Actual Deworming Status", y = "Proportion", title = "Reported and Actual Others' Deworming", subtitle = "Table A only",
#            caption = "Proportions are relative to deworming status group.") +
#       scale_y_continuous(breaks = seq(0, 1, 0.1)) +
#       scale_fill_discrete("Reported Others' Dewormed") +
#       facet_wrap(~ assigned.treatment, nrow = 1) +
#       # facet_grid(respondent.dewormed.any ~ assigned.treatment) + #, nrow = 1) +
#       theme(legend.position = "bottom")
#   }
```

```{r}
endline.know.table.data %>% 
  filter(know.table.type == "table.B") %>% { 
    ggplot(.) +
      geom_bar(aes(num.recognized, y = ..count../sum(..count..)), alpha = 0.5, color = "black") + 
      labs(x = "Number of Individuals Recognized", y = "Proportion", title = "Recognized in Pairs", subtitle = "Table B only", caption = sprintf("Number of knowledge queries: %d", nrow(.))) 
  }
```

```{r}
endline.know.table.data %>% 
  filter(know.table.type == "table.B", num.recognized > 0) %>%
  group_by(num.recognized) %>% 
  mutate(num.rec.size = n()) %>% 
  group_by(dewormed, add = TRUE) %>% 
  summarize(prop = n() / first(num.rec.size)) %>% 
  ungroup %>% { 
    ggplot(.) +
      geom_col(aes(factor(num.recognized), y = prop, fill = dewormed), position = "dodge", alpha = 0.5, color = "black") + 
      labs(x = "Number of Individuals Recognized", y = "Proportion", title = "Reported Others' Deworming (In Pairs)", subtitle = "Table B only", caption = "Proportions are relative to relationship group.") +
      scale_fill_discrete("Dewormed") +
      scale_y_continuous(breaks = seq(0, 1, 0.1))
  }
```

```{r, fig.height=6}
endline.know.table.data %>% 
  # filter(know.table.type == "table.B", num.recognized > 0) %>%
  filter(num.recognized > 0) %>%
  mutate(know.table.type = fct_recode(know.table.type, "Table A" = "table.A", "Table B" = "table.B")) %>% 
  group_by(assigned.treatment, know.table.type, actual.other.dewormed.any.either) %>% 
  mutate(num.rec.size = n()) %>% 
  group_by(dewormed, add = TRUE) %>% 
  summarize(prop = n() / first(num.rec.size)) %>% 
  ungroup %>% { 
    ggplot(.) +
      geom_col(aes(factor(actual.other.dewormed.any.either), y = prop, fill = dewormed), position = "dodge", alpha = 0.5, color = "black") + 
      labs(x = "Others' Actual Deworming Status", y = "Proportion", title = "Reported and Actual Others' Deworming", caption = "Proportions are relative to facet and actual deworming status groups.") +
      scale_fill_discrete("Others' Reported Deworming Status") +
      scale_y_continuous(breaks = seq(0, 1, 0.1)) +
      facet_grid(know.table.type ~ assigned.treatment) +
      theme(legend.position = "bottom")
      # facet_wrap(~ assigned.treatment, nrow = 1)
  }
```

```{r}
endline.know.table.data %>% 
  filter(know.table.type == "table.A", 
         recognized == "yes") %>% 
  group_by(KEY.individ, assigned.treatment, sms.treatment) %>% 
  mutate(num_rec = n()) %>% 
  group_by(dewormed, add = TRUE) %>% 
  summarize(prop_response = n() / sum(num_rec)) %>%
  group_by(assigned.treatment, sms.treatment, dewormed) %>% 
  summarize(prop_response = mean(prop_response, na.rm = TRUE)) %>%
  ungroup() %>% 
  ggplot(aes(factor(dewormed))) +
  geom_col(aes(y = prop_response, fill = sms.treatment), position = "dodge") +
  facet_wrap(~ assigned.treatment)

endline.know.table.data %>% 
  filter(know.table.type == "table.A", 
         recognized == "yes", 
         dewormed %in% c("no", "yes")) %>% 
  mutate(correct_response = (dewormed == "no" & !actual.other.dewormed.any.either) | (dewormed == "yes" & actual.other.dewormed.any.either)) %>% 
  group_by(KEY.individ, assigned.treatment, sms.treatment) %>% 
  summarize(prop_accurate = mean(correct_response, na.rm = TRUE), prop_dewormed = mean(dewormed == "yes"), prop_actual_dewormed = mean(actual.other.dewormed.any.either)) %>% 
  group_by(assigned.treatment, sms.treatment) %>%
  summarize_at(vars(prop_accurate, prop_dewormed, prop_actual_dewormed), funs(mean(., na.rm = TRUE)))
```

```{r, fig.width=10}
endline.data %>% 
  ggplot() +
  geom_freqpoly(aes(x = dworm_rate, y = ..density.., color = sms.treatment), binwidth = 1) +
  geom_vline(aes(xintercept = mean_belief, color = sms.treatment), 
             data = . %>% group_by(assigned.treatment, sms.treatment) %>% summarize(mean_belief = mean(dworm_rate, na.rm = TRUE))) +
  scale_x_continuous("Reported Rate", breaks = 0:10) +
  scale_y_continuous("Density") +
  scale_color_discrete("") +
  theme(legend.position = "bottom") +
  facet_wrap(~ assigned.treatment, ncol = 1)  

endline.data %>% 
  left_join(select(analysis.data, KEY.individ, dewormed.any), "KEY.individ") %>% 
  ggplot() +
  geom_freqpoly(aes(x = dworm_rate, y = ..density.., color = sms.treatment), binwidth = 1) +
  geom_vline(aes(xintercept = mean_belief, color = sms.treatment), 
             data = . %>% group_by(assigned.treatment, sms.treatment, dewormed.any) %>% summarize(mean_belief = mean(dworm_rate, na.rm = TRUE))) +
  scale_x_continuous("Reported Rate", breaks = 0:10) +
  scale_y_continuous("Density") +
  scale_color_discrete("") +
  theme(legend.position = "bottom") +
  facet_grid(assigned.treatment ~ dewormed.any)  
```

```{r, fig.height=20, fig.width=15}
takeup_beliefs <- select(endline.data, cluster.id, village, assigned.treatment, sms.treatment, dworm_rate) %>% 
  group_by(cluster.id, village, assigned.treatment, sms.treatment) %>% 
  summarize(takeup_rate = mean(dworm_rate, na.rm = TRUE)) %>% 
  ungroup() %>% 
  rename(rate_type = sms.treatment)

sms.content.data %>% 
  filter(deworming.day == 10, !is.na(KEY.individ), !is.na(social.info)) %>% 
  inner_join(select(analysis.data, KEY.individ, cluster.id, village, assigned.treatment), "KEY.individ") %>% 
  distinct(cluster.id, village, assigned.treatment, social.info) %>% 
  rename(takeup_rate = social.info) %>% 
  mutate(rate_type = "sms_content") %>% 
  bind_rows(takeup_beliefs) %>% 
  spread(rate_type, takeup_rate) %>% 
  mutate(village = factor(village) %>% fct_reorder(sms_content)) %>% 
  ggplot(aes(x = village)) +
  # geom_linerange(aes(ymin = 0, ymax = takeup_rate), size = 0.15) +
  # geom_point(aes(y = takeup_rate, color = rate_type), data = . %>% gather(rate_type, takeup_rate) %>% filter(rate_type != "sms_content")) +
  geom_segment(aes(xend = village, y = sms.control, yend = social.info), arrow = arrow(length = unit(0.125, "cm"))) +
  geom_point(aes(y = sms_content)) +
  labs(x = "", y = "") +
  coord_flip() +
  theme(axis.text.y = element_blank(), axis.ticks.y = element_blank()) +
  facet_wrap(~ assigned.treatment, ncol = 2, scales = "free_y")
```

# Bayesian Model

```{r load-stanfit}
# fit_version <- "param_beliefs_2981815"
fit_version <- "know_table_poolsms"
model_fit <- dir(file.path("data", "stanfit"), pattern = str_interp("model_${fit_version}_\\d+.csv"), full.names = TRUE) %>%
  read_stan_csv()

check_hmc_diagnostics(model_fit)

rhat(model_fit) %>% summary()

load(file.path("stan_analysis_data", str_interp("model_${fit_version}.RData")))
```

```{r}
model_fit %>% 
  print(pars = c("hyper_recognized_intercept", "hyper_recognized_beta_cluster_size", 
                 "cluster_recognized_intercept_sd",
                 "obs_recognized_intercept_sd",
                 "hyper_2ord_beta",
                 "cluster_2ord_beta_sd"))
```

```{r}
model_fit %>% 
  print(pars = c("fp_2ord_prop_knows_ate"), 
        probs = c(0.025, 0.05, 0.25, 0.5, 0.75, 0.95, 0.975)) 
```

## Analysis

```{r, include=FALSE}
treatment_cell_info <- param_stan_data$ate_treatments %>%
  mutate(treatment_size = with(param_stan_data, know_table_A_missing_treatment_sizes + know_table_A_observed_treatment_sizes)) %>%
  left_join(param_stan_data$treatment_map, "all_treatment_id") %>% 
  select(-ends_with("_id"), all_treatment_id) %>% 
  mutate(treatment_rank = seq_len(n()),
        observed_treatment_size = param_stan_data$know_table_A_observed_treatment_sizes) %>% 
         # observed_takeup_prop = param_stan_data$observed_takeup_total / observed_treatment_size) %>% 
  unite(incentive_treatment, str_c(c("private", "social"), "_value"), sep = "-", remove = FALSE) %>% 
  create_incentive_treatment_col()

ate_pair_info <- param_stan_data$ate_pairs %>% 
  mutate(pair_rank = seq_len(n())) %>% 
  left_join(treatment_cell_info, c("rank_id_left" = "treatment_rank")) %>% 
  left_join(treatment_cell_info, c("rank_id_right" = "treatment_rank"), suffix = c("_left", "_right")) %>% 
  mutate(treatment_size = treatment_size_left)

fp_1ord_prop_knows_mean <- model_fit %>% 
  as.data.frame(pars = "fp_1ord_prop_knows_mean") %>%
  mutate(iter_id = seq_len(n())) %>% 
  gather(treatment_rank, fp_1ord_prop_knows_mean, -iter_id) %>% 
  mutate(treatment_rank = str_extract_all(treatment_rank, "\\d+") %>% map_int(~ as.integer(.x[2]))) %>% 
  inner_join(treatment_cell_info, "treatment_rank") 

fp_1ord_prop_knows_ate <- model_fit %>% 
  as.data.frame(pars = "fp_1ord_prop_knows_ate") %>%
  mutate(iter_id = seq_len(n())) %>% 
  gather(outcome_id, iter_ate, -iter_id) %>% 
  mutate(pair_rank = str_extract_all(outcome_id, "\\d+") %>% map_int(~ as.integer(.x[2]))) %>% 
  inner_join(ate_pair_info, "pair_rank")

fp_2ord_prop_knows_mean <- model_fit %>% 
  as.data.frame(pars = "fp_2ord_prop_knows_mean") %>%
  mutate(iter_id = seq_len(n())) %>% 
  gather(treatment_rank, fp_2ord_prop_knows_mean, -iter_id) %>% 
  mutate(treatment_rank = str_extract_all(treatment_rank, "\\d+") %>% map_int(~ as.integer(.x[2]))) %>% 
  inner_join(treatment_cell_info, "treatment_rank") 

fp_2ord_prop_knows_ate <- model_fit %>% 
  as.data.frame(pars = "fp_2ord_prop_knows_ate") %>%
  mutate(iter_id = seq_len(n())) %>% 
  gather(outcome_id, iter_ate, -iter_id) %>% 
  mutate(pair_rank = str_extract_all(outcome_id, "\\d+") %>% map_int(~ as.integer(.x[2]))) %>% 
  inner_join(ate_pair_info, "pair_rank")
```

```{r 1ord-beliefs-levels, include=FALSE}
fp_1ord_prop_knows_mean_phone <- fp_1ord_prop_knows_mean %>% 
  prepare_fp_1ord_prop_knows_mean(subgroups = "phone_owner")

fp_1ord_prop_knows_mean_dist <- fp_1ord_prop_knows_mean %>% 
  prepare_fp_1ord_prop_knows_mean(subgroups = "dist.pot.group")

fp_1ord_prop_knows_mean_phone_dist <- fp_1ord_prop_knows_mean %>% 
  prepare_fp_1ord_prop_knows_mean(subgroups = c("phone_owner", "dist.pot.group"))

fp_1ord_prop_knows_mean_all <- fp_1ord_prop_knows_mean %>% 
  prepare_fp_1ord_prop_knows_mean()
```

```{r 2ord-beliefs-levels, include=FALSE}
fp_2ord_prop_knows_mean_phone <- fp_2ord_prop_knows_mean %>% 
  prepare_fp_2ord_prop_knows_mean(subgroups = "phone_owner")

fp_2ord_prop_knows_mean_dist <- fp_2ord_prop_knows_mean %>% 
  prepare_fp_2ord_prop_knows_mean(subgroups = "dist.pot.group")

fp_2ord_prop_knows_mean_phone_dist <- fp_2ord_prop_knows_mean %>% 
  prepare_fp_2ord_prop_knows_mean(subgroups = c("phone_owner", "dist.pot.group"))

fp_2ord_prop_knows_mean_all <- fp_2ord_prop_knows_mean %>% 
  prepare_fp_2ord_prop_knows_mean()
```

```{r 1ord-beliefs-ate, include=FALSE}
fp_1ord_prop_knows_ate_phone <- fp_1ord_prop_knows_ate %>%
  filter(dist.pot.group_left == dist.pot.group_right) %>% 
  prepare_fp_1ord_prop_knows_ate(subgroups = "phone_owner_left")

fp_1ord_prop_knows_ate_dist <- fp_1ord_prop_knows_ate %>%
  prepare_fp_1ord_prop_knows_ate(subgroups = str_c("dist.pot.group", c("_left", "_right")))

fp_1ord_prop_knows_ate_phone_dist <- fp_1ord_prop_knows_ate %>%
  prepare_fp_1ord_prop_knows_ate(subgroups = c("phone_owner_left", str_c("dist.pot.group", c("_left", "_right"))))

fp_1ord_prop_knows_ate_all <- fp_1ord_prop_knows_ate %>%
  filter(dist.pot.group_left == dist.pot.group_right) %>% 
  prepare_est_deworming_ate() 
```

```{r 2ord-beliefs-ate, include=FALSE}
fp_2ord_prop_knows_ate_phone <- fp_2ord_prop_knows_ate %>%
  filter(dist.pot.group_left == dist.pot.group_right) %>% 
  prepare_fp_2ord_prop_knows_ate(subgroups = "phone_owner_left")

fp_2ord_prop_knows_ate_dist <- fp_2ord_prop_knows_ate %>%
  prepare_fp_2ord_prop_knows_ate(subgroups = str_c("dist.pot.group", c("_left", "_right")))

fp_2ord_prop_knows_ate_phone_dist <- fp_2ord_prop_knows_ate %>%
  prepare_fp_2ord_prop_knows_ate(subgroups = c("phone_owner_left", str_c("dist.pot.group", c("_left", "_right"))))

fp_2ord_prop_knows_ate_all <- fp_2ord_prop_knows_ate %>%
  filter(dist.pot.group_left == dist.pot.group_right) %>% 
  prepare_est_deworming_ate() 
```

```{r}
save(
  ate_pair_info,
  fp_1ord_prop_knows_mean,
  fp_1ord_prop_knows_ate,
  fp_2ord_prop_knows_mean, 
  fp_2ord_prop_knows_ate, 
  fp_1ord_prop_knows_mean_phone,
  fp_1ord_prop_knows_mean_dist,
  fp_1ord_prop_knows_mean_phone_dist,
  fp_1ord_prop_knows_mean_all,
  fp_2ord_prop_knows_mean_phone,
  fp_2ord_prop_knows_mean_dist,
  fp_2ord_prop_knows_mean_phone_dist,
  fp_2ord_prop_knows_mean_all,
  fp_1ord_prop_knows_ate_phone,
  fp_1ord_prop_knows_ate_dist,
  fp_1ord_prop_knows_ate_phone_dist,
  fp_1ord_prop_knows_ate_all,
  fp_2ord_prop_knows_ate_phone,
  fp_2ord_prop_knows_ate_dist,
  fp_2ord_prop_knows_ate_phone_dist,
  fp_2ord_prop_knows_ate_all,
  
  file = file.path("stan_analysis_data", "beliefs_processed.RData")
)
```


$$
\begin{align}
  Y_i^\text{rec} &\sim \mathtt{Binomial}(10, p_i^\text{rec}) \\
  p_i^\text{rec} &= logit^{-1}(\alpha_i^\text{rec} + \delta_{j[i]}^\text{rec}\cdot N_{j[i]}) \\
  X_i^{degree} &= Y_i^\text{rec} + p^\text{rec}_i \cdot(N_{j[i]} - 10)  
\end{align}
$$

$$
\begin{align}
  Y_i^\text{2ord} &\sim \mathtt{Binomial}(Y^\text{rec}_i, p_i^\text{2ord}(\mathbf{Z}_i)) \\
  p_i^\text{2ord}(\mathbf{z}) &= logit^{-1}(\alpha_i^\text{2ord} + \mathbf{z}\cdot \beta_i^\text{2ord} + \delta_i^\text{2ord}\cdot N_{j[i]}) \\
  \overline{Y}^\text{ 2ord,fp}(\mathbf{Z}_i) &= \frac{Y_i^\text{2ord} + p_i^\text{2ord}(\mathbf{Z}_i)\cdot p_i^\text{rec}\cdot (N_j[i] - 10)}{X_i^{degree}}
\end{align}
$$

For unobserved (missing) treatment $\mathbf{z}^\text{mis}$ we impute $\overline{Y}^\text{ 2ord,fp}(\mathbf{z}^\text{mis})$ as
$$
  \overline{Y}^\text{ 2ord,fp}(\mathbf{z}^\text{mis}) = \frac{p_i^\text{2ord}(\mathbf{z}^\text{mis})\cdot p_i^\text{rec}\cdot N_j[i]}{X_i^{degree}}
$$

### Pooled SMS Treatment

#### Levels

```{r, fig.width=8}
plot_takeup(
  takeup_summ_data = fp_1ord_prop_knows_mean_all,
  data_preparer = . %>%
    filter(
      incentive_treatment != "Bracelet Social"
      ),
  incentive_treatment_col = "incentive_treatment",
  show_observed = FALSE
    ) +
  labs(title = "First Order Beliefs (Levels)", 
       subtitle = "Proportion of recognized peers whose deworming status is reported known", y = "") 
```

```{r, fig.width=8, fig.height=8}
plot_takeup(
  takeup_summ_data = fp_1ord_prop_knows_mean_phone,
  data_preparer = . %>%
    filter(
      incentive_treatment != "Bracelet Social"
      ) %>% 
      mutate_at(vars(starts_with("phone_owner")), funs(factor(., levels = c(FALSE, TRUE), labels = c("Non-Phone Owners", "Phone Owners")))), 
  incentive_treatment_col = "incentive_treatment",
  show_observed = FALSE
    ) +
  labs(title = "First Order Beliefs (Levels)", 
       subtitle = "Proportion of recognized peers whose deworming status is reported known", y = "") +
  facet_wrap(~ phone_owner, ncol = 1) 
  # theme(strip.text = element_text(size = 15, face = "bold"))
```

```{r, fig.width=8}
plot_takeup(
  takeup_summ_data = fp_2ord_prop_knows_mean_all,
  data_preparer = . %>%
    filter(
      incentive_treatment != "Bracelet Social"
      ),
  incentive_treatment_col = "incentive_treatment",
  show_observed = FALSE
    ) +
  labs(title = "Second Order Beliefs (Levels)", 
       subtitle = "Proportion of recognized peers with knowledge of one's deworming status", y = "") 
```

```{r, fig.width=8, fig.height=8}
plot_takeup(
  takeup_summ_data = fp_2ord_prop_knows_mean_phone,
  data_preparer = . %>%
    filter(
      incentive_treatment != "Bracelet Social"
      ) %>% 
      mutate_at(vars(starts_with("phone_owner")), funs(factor(., levels = c(FALSE, TRUE), labels = c("Non-Phone Owners", "Phone Owners")))), 
  incentive_treatment_col = "incentive_treatment",
  show_observed = FALSE
    ) +
  labs(title = "Second Order Beliefs (Levels)", 
       subtitle = "Proportion of recognized peers with knowledge of one's deworming status", y = "") +
  facet_wrap(~ phone_owner, ncol = 1) 
  # theme(strip.text = element_text(size = 15, face = "bold"))
```

#### ATE

```{r, fig.width=8, fig.height=4}
fp_1ord_prop_knows_ate_all %>%
  filter(incentive_treatment_left != "bracelet social",
         !(incentive_treatment_left == "bracelet" & incentive_treatment_right == "calendar")) %>%
  plot_ate(
    ate_summ_data = .,
      data_preparer = . %>% 
      filter(incentive_treatment_right %in% c("Control", "Calendar"),
             incentive_treatment_left != incentive_treatment_right),
    incentive_treatment_left_col = "incentive_treatment_left" 
  ) + 
  labs(title = "First Order Beliefs (ATE)", 
       subtitle = "Average change in the proportion of recognized peers whose deworming status is reported known", 
       y = "") 
```

```{r, fig.width=8, fig.height=7}
fp_1ord_prop_knows_ate_phone %>%
  filter(incentive_treatment_left != "bracelet social",
         !(incentive_treatment_left == "bracelet" & incentive_treatment_right == "calendar")) %>%
  plot_ate(
    ate_summ_data = .,
      data_preparer = . %>% 
      filter(incentive_treatment_right %in% c("Control", "Calendar"),
             incentive_treatment_left != incentive_treatment_right) %>% 
      mutate_at(vars(starts_with("phone_owner")), funs(factor(., levels = c(FALSE, TRUE), labels = c("Non-Phone Owners", "Phone Owners")))), 
    incentive_treatment_left_col = "incentive_treatment_left" 
  ) + 
  labs(title = "First Order Beliefs (ATE)", 
       subtitle = "Average change in the proportion of recognized peers whose deworming status is reported known", 
       y = "") +
  facet_wrap(~ phone_owner_left, ncol = 1) 
```

```{r, fig.width=8, fig.height=4}
fp_2ord_prop_knows_ate_all %>%
  filter(incentive_treatment_left != "bracelet social",
         !(incentive_treatment_left == "bracelet" & incentive_treatment_right == "calendar")) %>%
  plot_ate(
    ate_summ_data = .,
      data_preparer = . %>% 
      filter(incentive_treatment_right %in% c("Control", "Calendar"),
             incentive_treatment_left != incentive_treatment_right),
    incentive_treatment_left_col = "incentive_treatment_left" 
  ) + 
  labs(title = "Second Order Beliefs (ATE)", 
       subtitle = "Average change in the proportion of recognized peers with knowledge of one's deworming status",
       y = "")
```

```{r, fig.width=8, fig.height=7}
fp_2ord_prop_knows_ate_phone %>%
  filter(incentive_treatment_left != "bracelet social",
         !(incentive_treatment_left == "bracelet" & incentive_treatment_right == "calendar")) %>%
  plot_ate(
    ate_summ_data = .,
      data_preparer = . %>% 
      filter(incentive_treatment_right %in% c("Control", "Calendar"),
             incentive_treatment_left != incentive_treatment_right) %>% 
      mutate_at(vars(starts_with("phone_owner")), funs(factor(., levels = c(FALSE, TRUE), labels = c("Non-Phone Owners", "Phone Owners")))), 
    incentive_treatment_left_col = "incentive_treatment_left" 
  ) + 
  labs(title = "Second Order Beliefs (ATE)", 
       subtitle = "Average change in the proportion of recognized peers with knowledge of one's deworming status",
       y = "") +
  facet_wrap(~ phone_owner_left, ncol = 1) 
```

### All Combined

#### Levels

```{r, fig.width=8, eval=FALSE}
plot_takeup(
  takeup_summ_data = fp_2ord_prop_knows_mean_all,
  data_preparer = . %>%
    filter(
      sms.treatment.2 == "control",
      incentive_treatment != "Bracelet Social"
      ),
  incentive_treatment_col = "incentive_treatment",
  show_observed = FALSE
    ) +
  labs(title = "Second Order Beliefs", subtitle = "Proportion of recognized peers who know one's deworming status", y = "") 
```

```{r, fig.width=8, eval=FALSE}
plot_takeup(
  takeup_summ_data = fp_2ord_prop_knows_mean_phone,
  data_preparer = . %>%
    filter(
      phone_owner,
      incentive_treatment != "Bracelet Social"
      ),
  incentive_treatment_col = "incentive_treatment",
  sms_treatment_col = "sms.treatment.2",
  include_sms_treatment = TRUE,
  show_observed = FALSE
    ) +
  labs(title = "Second Order Beliefs", subtitle = "Proportion of recognized peers who know one's deworming status (phone owners only)", y = "") 
```

#### ATE

```{r, fig.width=8, fig.height=4, eval=FALSE}
fp_2ord_prop_knows_ate_all %>%
  filter(incentive_treatment_left != "bracelet social",
         !(incentive_treatment_left == "bracelet" & incentive_treatment_right == "calendar")) %>%
  plot_ate(
    ate_summ_data = .,
      data_preparer = . %>% 
      filter(incentive_treatment_right %in% c("Control", "Calendar"),
             incentive_treatment_left != incentive_treatment_right,
             sms.treatment.2_left == "control",
             sms.treatment.2_left == sms.treatment.2_right),
    incentive_treatment_left_col = "incentive_treatment_left" 
  ) + 
  labs(title = "Second Order Beliefs ATE", y = "")
```

```{r, fig.width=8, eval=FALSE}
fp_2ord_prop_knows_ate_phone %>%
  mutate(same_incentive = incentive_treatment_left == incentive_treatment_right,
         same_sms = sms.treatment.2_left == sms.treatment.2_right) %>% 
  filter(phone_owner_left, 
         incentive_treatment_left != "bracelet social",
         !same_incentive & same_sms,
         sms.treatment.2_right != "reminder.only",
         !(incentive_treatment_left == "bracelet" & incentive_treatment_right == "calendar")) %>% 
  plot_ate(
    ate_summ_data = .,
    incentive_treatment_left_col = "incentive_treatment_left",
    sms_treatment_col = "sms.treatment.2_left",
    include_sms_treatment = TRUE
  ) + 
  labs(title = "Second Order Beliefs ATE", y = "", subtitle = "Phone owners only")
```

## Model Checking

```{r}
recognized_prop <- param_stan_data$num_know_table_A_recognized / 10
thinks_1ord_knows_prop <- param_stan_data$num_know_table_A_1ord_knows / na_if(param_stan_data$num_know_table_A_recognized, 0)
thinks_knows_prop <- param_stan_data$num_know_table_A_2ord_knows / na_if(param_stan_data$num_know_table_A_recognized, 0)
  
rep_recognized_prop <- model_fit %>% as.matrix("rep_know_table_A_prop_recognized")
rep_1ord_knows_prop <- model_fit %>% as.matrix("rep_know_table_A_1ord_prop_know")
rep_2ord_knows_prop <- model_fit %>% as.matrix("rep_know_table_A_2ord_prop_know")
```

```{r}
ppc_dens_overlay(recognized_prop, rep_recognized_prop)
ppc_dens_overlay(thinks_1ord_knows_prop[!is.na(thinks_1ord_knows_prop)], rep_1ord_knows_prop[, !is.na(thinks_1ord_knows_prop)]) 
ppc_dens_overlay(thinks_knows_prop[!is.na(thinks_knows_prop)], rep_2ord_knows_prop[, !is.na(thinks_knows_prop)]) 
```


