---
title: "Prosocial Signaling Model"
output: pdf_document
bibliography: /home/karim/Documents/library.bib
header-includes:
   - \usepackage{pxfonts}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

I plan to use ABM to model the utility maximizing behavior of agents (i) motivated by their prosocial (altruistic) type; (ii) motivated by the reputational returns to signaling their prosocial actions, and (iii) influenced by their peers on observing their actions (social learning). This phenomenon is based on Bénabou and Tirole's theoretical work^[Henceforth, referred to as BT.] [-@Benabou2006;-@Benabou2012]. Their model focuses on the equilibrium outcomes of agents interacting solely via how their choices are used to infer their prosocial type. My goal is to introduce greater heterogeneity in the channels of communication/observation between agents; introduce heterogeneity in the prior beliefs and uncertainty agents have about the distribution of altruism in their community; allow agents to choose whether to signal their choices to others or not; and to add the possibility of social learning (similar to the diffusion models studied in this course), thus they are motivated by both the possibility to broadcast their prosocial type, as well as learn from others the benefit of taking particular actions.

Therefore, if agents are confronted with a discrete choice of whether to take a potentially socially beneficial action, $a \in \{0,1\}$, they would do so if 

\begin{equation*}
v + y + x\delta (E[\tilde{v} | \tilde{v} > v^*] - E[\tilde{v} | \tilde{v} \leq v^*]) > 0, 
\end{equation*}
where

* $v$ is their unobservable prosocial type.
* $y$ is the private benefit/cost of taking action $a = 1$.
* $x$ is the degree to which their action is observable to others, depending on what signaling mechanisms are available to them.
* $\delta$ is the social desirability of being prosocial.
* $v^*$ is the prosocial type _cutoff_ that determines the reputational returns to taking action $a = 1$; individuals observed taking such an action are assumed to have $v > v^*$ and $v \leq v^*$ otherwise. 

In the BT model, the distribution of $v$ is assumed to be known by all agents and $v^*$ is correctly known by all in equilibrium.

# Responses to the Model Questionnaire {-}

1. The two main parts of this phenomenon that I want to model are the evolving beliefs of $v^*$ and $y$: beliefs about the reputational and private returns to taking a particular action. 
2. There is really only one type of agent choosing their optimal action. Heterogeneity among agents is driven by their prosocial type. Such agents would be able to gather information from their networks (or spatial peers), choose an action, and choose whether to utilize available signaling mechanisms. There is also potentially a _proto-agent_ type representing the providers of signaling mechanisms. These proto-agents would vary in the cost of accessing their signal (perhaps due to the distance agents would have to cover to reach them). 
3. The main properties of agents would be their prosocial type, $v$, their network peers, and their prior beliefs about the distribution of $v$ and $y$. 
4. Agents choose an action $a \in \{0, 1\}$ and potentially choose $x \leq \bar{x}$, where $\bar{x}$ is the maximum degree of signaling available to them.
5. Agents either:
    a) Exist in a bidirectional network where network characteristics (e.g., centrality) is correlated to $v$ (morally outstanding citizens perhaps have more influence and are more knowledgeable of their community's choices). 
    b) Exist spatially where they have greater observability of their peers and perhaps have some commonalities with respect to cost of taking an action and/or signaling their choice.
6. In each time step agents would observe the action of their peers in the previous time step (depending on signaling), decide what action to take and whether to signal such an action, depending on inferred utility. Mainly I have been thinking of a model with one-time action but with the signaling mutable at each step (conditional on having having chosen $a = 1$ since only truthful signaling is allowed).
7. Inputs include the distribution of $v$, the prior beliefs of agents about this distribution, the range/availability of signaling ($x$), whether signaling is voluntary on taking action, the social desirability of prosocial action ($\delta$), and the distribution of costs for actions and signals. 
8. I am in particular interested in how signaling would influence the degree of action take-up and how it would interact with the environment individuals are located in and the cost of action/signaling---how would a policy-maker be able to use signaling to increase the take-up of action that might have low private returns but high social returns (e.g., vaccination or voting).


# References {-}

<div id="refs"></div>